---
- name: (Package) Install GPG if needed for repo signing
  ansible.builtin.apt:
    name: gpg
    state: present
    update_cache: true
  when: nginx_official_repo_enabled | bool

- name: (Package) Create keyrings directory
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: "0755"
  when: nginx_official_repo_enabled | bool

- name: (Package) Download official Nginx signing key
  ansible.builtin.get_url:
    url: "{{ __nginx_repo_key_url }}"
    dest: /tmp/nginx_signing.key
    mode: "0644"
  when: nginx_official_repo_enabled | bool

- name: (Package) Dearmor and install Nginx signing key
  ansible.builtin.shell:
    cmd: gpg --dearmor < /tmp/nginx_signing.key > /usr/share/keyrings/nginx-archive-keyring.gpg
    creates: /usr/share/keyrings/nginx-archive-keyring.gpg
  when: nginx_official_repo_enabled | bool

- name: (Package) Set keyring permissions
  ansible.builtin.file:
    path: /usr/share/keyrings/nginx-archive-keyring.gpg
    mode: "0644"
  when: nginx_official_repo_enabled | bool

- name: (Package) Add official Nginx repository
  ansible.builtin.apt_repository:
    repo: "{{ __nginx_repo }}"
    state: present
    filename: nginx
    update_cache: true
  when: nginx_official_repo_enabled | bool

- name: (Package) Install nginx packages
  ansible.builtin.apt:
    name: "{{ __nginx_packages + nginx_extra_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
