---
- name: Gather OS facts if not available
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "distribution"
      - "os_family"
  when: ansible_os_family is not defined

- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"

- name: Install Nginx
  ansible.builtin.include_tasks: "install-{{ nginx_install_method }}.yml"

- name: Configure Virtual Hosts
  ansible.builtin.include_tasks: "vhosts.yml"

- name: Configure Upstreams
  ansible.builtin.include_tasks: "upstreams.yml"
  when: nginx_upstreams | length > 0

- name: Configure SSL
  ansible.builtin.include_tasks: "ssl.yml"
  when: nginx_ssl_enabled | bool

- name: Configure Let's Encrypt
  ansible.builtin.include_tasks: "letsencrypt.yml"
  when: nginx_letsencrypt_enabled | bool

- name: Deploy Custom SSL Certificates
  ansible.builtin.include_tasks: "custom-certs.yml"
  when: nginx_custom_ssl_certificates | length > 0

- name: Configure Nginx
  ansible.builtin.include_tasks: "configure.yml"

- name: Configure Stream Proxy
  ansible.builtin.include_tasks: "stream.yml"
  when: nginx_stream_enabled | bool

- name: Manage Nginx Service
  ansible.builtin.include_tasks: "service.yml"
